// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmhfbsmtmlsjvzvallkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaGZic210bWxzanZ6dmFsbGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTExNDMsImV4cCI6MjA2MjcyNzE0M30.0G_YyBbkKQCMZD9IHHGHC_eyWETVqQf3_rg-TeGCCbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: {
      // Use localStorage for better persistence across tabs/sessions
      getItem: (key) => localStorage.getItem(key),
      setItem: (key, value) => localStorage.setItem(key, value),
      removeItem: (key) => localStorage.removeItem(key),
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});